./roles/icinga2_client/meta/main.yml
./roles/icinga2_icingaweb2/meta/main.yml
./roles/monitoring_plugins/meta/main.yml
./roles/icinga2_checks/meta/main.yml
./roles/icinga2_master/meta/main.yml
./roles/icinga2_hostconfig/meta/main.yml
./galaxy.yml
./playbooks/roles/icinga2_client/meta/main.yml
./playbooks/roles/icinga2_icingaweb2/meta/main.yml
./playbooks/roles/monitoring_plugins/meta/main.yml
./playbooks/roles/icinga2_checks/meta/main.yml
./playbooks/roles/icinga2_master/meta/main.yml
./playbooks/roles/icinga2_hostconfig/meta/main.yml
