---
# description: icinga2 checks source path(s)
#              location where the check templates are stored, will be copied recursively
#              can be a full path or relative to the role tasks directory
# type: list
icinga2_checks_src:
  - "../templates/checks/"

# description: ntp server to use for chrony/ntp checks (ip or hostname)
# type: string
icinga2_checks_ntp_server: "10.1.2.3"

# description: load check values
#              warning and critical values for 1, 5 and 15 minutes
# type: dict
icinga2_checks_load:
  wload1: "2.0"
  wload5: "1.5"
  wload15: "1.0"
  cload1: "4.0"
  cload5: "3.0"
  cload15: "2.0"

# description: procs warning and critical values
# type: dict
icinga2_checks_procs:
  warning: 6000
  critical: 8000

# description: warning and critical amount for the number of users on a system
# type: dict
icinga2_checks_users:
  warning: 30
  critical: 50

# description: default credentials for the mysql monitoring user
# type: dict
icinga2_checks_mysql:
  user: monitorit
  pass: readonly
