---
- name: icinga2 master
  hosts: icinga2master
  become: true

  roles:
    - role: monitoring_plugins
      tags:
        - plugins
        - monitoring-plugins
    - role: icinga2_master
      tags:
        - master
    - role: icinga2_hostconfig
    - role: icinga2_checks
      tags:
        - checks
    - role: icinga2_hostconfig
      tags:
        - hostconfig
    - role: icinga2_icingaweb2
      tags:
        - icingaweb
